Repository edgexfoundry/edgex-go, pull requests merged in 2019-07, with the labels that each got.

#1498 Add validation when update device profile
  api/raml/core-metadata.raml
  go.mod
  internal/core/metadata/errors/types.go
  internal/core/metadata/operators/device/db.go
  internal/core/metadata/operators/device/get.go
  internal/core/metadata/operators/device/get_test.go
  internal/core/metadata/operators/device/mocks/DeviceLoader.go
  internal/core/metadata/operators/device_profile/db.go
  internal/core/metadata/operators/device_profile/mocks/DeviceProfileUpdater.go
  internal/core/metadata/operators/device_profile/update.go
  internal/core/metadata/operators/device_profile/update_test.go
  internal/core/metadata/rest_deviceprofile.go
  internal/core/metadata/rest_deviceprofile_test.go
Labels: enhancement, fuji

#1510 Update reference to go-mod-messaging, fix race condition
  go.mod
  internal/core/data/event.go
Labels: bug, core-services, edinburgh

#1508 Unit Testability -- core-metadata/GetAllDeviceServices
  internal/core/metadata/operators/device_service/db.go
  internal/core/metadata/operators/device_service/get.go
  internal/core/metadata/operators/device_service/get_test.go
  internal/core/metadata/operators/device_service/mocks/DeviceServiceLoader.go
  internal/core/metadata/rest_deviceservice.go
  internal/core/metadata/rest_deviceservice_test.go
Labels: core-services, enhancement, fuji

#1511 Update reference to go-mod-messaging, fix race condition (master)
  go.mod
  internal/core/data/event.go
Labels: bug, core-services, fuji

#1516 Updated Consul to 1.5.2.
  go.mod
Labels: fuji

#1550 Patch docker-compose timing issues in export/rules-engine
  VERSION
  go.mod
  internal/core/command/init.go
  internal/core/data/init.go
  internal/core/metadata/init.go
  internal/export/client/init.go
  internal/export/client/registration.go
  internal/export/distro/init.go
  internal/pkg/startup/endpoint.go
  internal/support/logging/init.go
  internal/support/notifications/init.go
  internal/support/scheduler/init.go
  version.go
Labels: bug, edinburgh

#1577 Update GetDeviceProfile APIs to use operators
  internal/core/metadata/operators/device_profile/db.go
  internal/core/metadata/operators/device_profile/delete_test.go
  internal/core/metadata/operators/device_profile/get.go
  internal/core/metadata/operators/device_profile/get_test.go
  internal/core/metadata/operators/device_profile/mocks/DeviceProfileDeleter.go
  internal/core/metadata/operators/device_profile/mocks/DeviceProfileLoader.go
  internal/core/metadata/operators/device_profile/mocks/DeviceProfileUpdater.go
  internal/core/metadata/operators/device_profile/update_test.go
  internal/core/metadata/rest_deviceprofile.go
  internal/core/metadata/rest_deviceprofile_test.go
Labels: enhancement, fuji

#1576 snapcraft.yaml: update sec-secret-store binary locations
  snap/snapcraft.yaml
Labels: fuji, snap

#1557 Relocate ValueDescriptor creation responsibility
  cmd/core-metadata/res/configuration.toml
  cmd/core-metadata/res/docker/configuration.toml
  go.mod
  internal/core/data/errors/types.go
  internal/core/metadata/config.go
  internal/core/metadata/init.go
  internal/core/metadata/operators/device_profile/mocks/ValueDescriptorAdder.go
  internal/core/metadata/operators/device_profile/mocks/ValueDescriptorUpdater.go
  internal/core/metadata/operators/device_profile/update.go
  internal/core/metadata/operators/device_profile/update_test.go
  internal/core/metadata/operators/device_profile/value_descriptor.go
  internal/core/metadata/operators/device_profile/value_descriptor_test.go
  internal/core/metadata/rest_deviceprofile.go
  internal/core/metadata/rest_deviceprofile_test.go
Labels: enhancement, fuji

#1604 Adding SonarCloud Config for AutoScan
  .sonarcloud.properties
Labels: enhancement, fuji
