Repository edgexfoundry/edgex-go, pull requests merged in 2019-08, with the labels that each got.

#1660 Removed Requestor interface, use HttpCaller instead
  internal/mocks/HttpCaller.go
  internal/security/proxy/certs.go
  internal/security/proxy/certs_test.go
  internal/security/proxy/consumer.go
  internal/security/proxy/requestor.go
  internal/security/proxy/resource.go
  internal/security/proxy/service.go
Labels: security-services

#1661 Fixing indentation security-proxy-setup configuration.toml files
  cmd/security-proxy-setup/res/configuration.toml
  cmd/security-proxy-setup/res/docker/configuration.toml
  internal/security/proxy/testdata/configuration.toml
Labels: security-services

#1663 Add missing validation for DeviceProfile APIs
  internal/core/metadata/operators/device_profile/value_descriptor.go
  internal/core/metadata/operators/device_profile/value_descriptor_test.go
  internal/core/metadata/rest_deviceprofile.go
  internal/core/metadata/rest_deviceprofile_test.go
Labels: bug, fuji

#1682 snap/README.md: update LXD section
  snap/README.md
Labels: documentation, snap

#1691 Added operator, unit test and REST test for GetDeviceServiceById
  internal/core/metadata/operators/device_service/db.go
  internal/core/metadata/operators/device_service/get.go
  internal/core/metadata/operators/device_service/get_test.go
  internal/core/metadata/operators/device_service/mocks/DeviceServiceLoader.go
  internal/core/metadata/operators/device_service/mocks/DeviceServiceUpdater.go
  internal/core/metadata/operators/device_service/update_test.go
  internal/core/metadata/rest_addressable_test.go
  internal/core/metadata/rest_deviceservice.go
  internal/core/metadata/rest_deviceservice_test.go
Labels: fuji

#1694 Added operator, unit and REST tests for DeviceServiceGetById
  internal/core/metadata/operators/device_service/get.go
  internal/core/metadata/operators/device_service/get_test.go
  internal/core/metadata/rest_deviceservice.go
  internal/core/metadata/rest_deviceservice_test.go
Labels: fuji

#1685 Apply Operator Pattern - Scrub Intervals
  internal/support/scheduler/interval.go
  internal/support/scheduler/operators/interval/db.go
  internal/support/scheduler/operators/interval/delete.go
  internal/support/scheduler/operators/interval/delete_test.go
  internal/support/scheduler/operators/interval/mocks/IntervalDeleter.go
  internal/support/scheduler/rest_interval.go
  internal/support/scheduler/rest_interval_test.go
  internal/support/scheduler/router.go
Labels: fuji

#1687 Apply Operator Pattern - Notification Get Newest
  internal/support/notifications/operators/notification/db.go
  internal/support/notifications/operators/notification/get.go
  internal/support/notifications/operators/notification/get_test.go
  internal/support/notifications/operators/notification/mocks/NotificationLoader.go
  internal/support/notifications/rest_notification.go
  internal/support/notifications/rest_notification_test.go
  internal/support/notifications/router.go
Labels: fuji

#1679 Fix update DeviceProfile API handling of name
  internal/core/metadata/operators/device_profile/update.go
  internal/core/metadata/operators/device_profile/update_test.go
Labels: bug, fuji

#1678 Update restAddProfileByYaml response code
  internal/core/metadata/rest_deviceprofile.go
  internal/core/metadata/rest_deviceprofile_test.go
Labels: bug, fuji

#1701 Unit test -- Core-Metadata Get Device Service By Name/ Addressable Name
  internal/core/metadata/operators/addressable/delete.go
  internal/core/metadata/operators/addressable/delete_test.go
  internal/core/metadata/operators/device_service/db.go
  internal/core/metadata/operators/device_service/get.go
  internal/core/metadata/operators/device_service/get_test.go
  internal/core/metadata/operators/device_service/mocks/DeviceServiceLoader.go
  internal/core/metadata/operators/device_service/mocks/DeviceServiceUpdater.go
  internal/core/metadata/rest_addressable.go
  internal/core/metadata/rest_deviceservice.go
  internal/core/metadata/rest_deviceservice_test.go
Labels: fuji

#1715 Fixed timeout not respected bug in all services; commonized server logic
  cmd/core-data/main.go
  cmd/core-metadata/main.go
  cmd/support-logging/main.go
  cmd/support-notifications/main.go
  cmd/support-scheduler/main.go
  cmd/sys-mgmt-agent/main.go
  internal/pkg/startup/server.go
  internal/support/logging/router.go
  internal/support/logging/router_test.go
Labels: bug, fuji
