Repository edgexfoundry/edgex-go, pull requests merged in 2020-06, with the labels that each got.

#2571 Tech-debt: removing "legacy" sub-command
  cmd/security-secrets-setup/entrypoint.sh
  cmd/security-secrets-setup/main_test.go
  internal/security/secrets/command/common.go
  internal/security/secrets/command/legacy/legacy.go
  internal/security/secrets/init.go
Labels: hanoi, security-services

#2590 doc: update pr template to include dependencies section
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#2601 build: revert explicit nexus tagging due to build failures
  Makefile
Labels: bug, ci
