Repository edgexfoundry/edgex-go, pull requests merged in 2020-07, with the labels that each got.

#2567 chore: Remove security services initialization for mongodb
  cmd/security-file-token-provider/res/token-config.json
  internal/security/secretread/types.go
  internal/security/secretstore/init.go
Labels: security-services

#2634 build: updates for new Jenkins pipeline.
  Dockerfile.build
  Jenkinsfile
  Makefile
  cmd/core-command/Dockerfile
  cmd/core-data/Dockerfile
  cmd/core-metadata/Dockerfile
  cmd/security-proxy-setup/Dockerfile
  cmd/security-secrets-setup/Dockerfile
  cmd/security-secretstore-setup/Dockerfile
  cmd/support-logging/Dockerfile
  cmd/support-notifications/Dockerfile
  cmd/support-scheduler/Dockerfile
  cmd/sys-mgmt-agent/Dockerfile
Labels: 2-medium, enhancement, hanoi

#2637 semver(master): set version next version to 1.2.1-dev.1
  master
Labels: 1-low, ci

#2641 fix: Fix path dependency in tokenprovider_linux_test.go
  internal/security/secretstore/tokenprovider_linux_test.go
Labels: bug

#2645 build: remove VERSION file as git-semver now manages version
  .gitignore
  Makefile
  VERSION
  snap/snapcraft.yaml
Labels: 2-medium, ci, hanoi
