Repository edgexfoundry/edgex-go, pull requests merged in 2020-04, with the labels that each got.

#2472 Fix Blackbox Testing issue #424
  cmd/security-proxy-setup/res/configuration.toml
  internal/security/proxy/testdata/configuration.toml
Labels: 3-high, bug, core-services, geneva

#2474 Implement ability to add additional Kong routes
  internal/security/proxy/service.go
  internal/security/proxy/service_test.go
Labels: 2-medium, enhancement, security-services

#2483 Set Empty LogFile Path for All Services
  cmd/core-command/res/configuration.toml
  cmd/core-data/res/configuration.toml
  cmd/core-metadata/res/configuration.toml
  cmd/security-proxy-setup/res/configuration.toml
  cmd/security-secrets-setup/res/configuration.toml
  cmd/security-secretstore-setup/res/configuration.toml
  cmd/support-logging/res/configuration.toml
  cmd/support-notifications/res/configuration.toml
  cmd/support-scheduler/res/configuration.toml
  cmd/sys-mgmt-agent/res/configuration.toml
  go.mod
Labels: 2-medium, core-services, enhancement, geneva

#2490 Swap ugorji/go with fxamacker/cbor library
  cmd/core-command/Attribution.txt
  cmd/core-data/Attribution.txt
  cmd/core-metadata/Attribution.txt
  cmd/security-file-token-provider/Attribution.txt
  cmd/security-proxy-setup/Attribution.txt
  cmd/security-secrets-setup/Attribution.txt
  cmd/security-secretstore-setup/Attribution.txt
  cmd/support-logging/Attribution.txt
  cmd/support-notifications/Attribution.txt
  cmd/support-scheduler/Attribution.txt
  cmd/sys-mgmt-agent/Attribution.txt
  cmd/sys-mgmt-executor/Attribution.txt
  go.mod
  internal/core/data/io.go
Labels: geneva, security_audit

#2040 doc: Save to docker-compose.yml
  README.md
Labels: documentation, geneva

#2510 Update version of go-mod-messaging
  cmd/core-command/Attribution.txt
  cmd/core-data/Attribution.txt
  cmd/core-metadata/Attribution.txt
  cmd/security-file-token-provider/Attribution.txt
  cmd/security-proxy-setup/Attribution.txt
  cmd/security-secrets-setup/Attribution.txt
  cmd/security-secretstore-setup/Attribution.txt
  cmd/support-logging/Attribution.txt
  cmd/support-notifications/Attribution.txt
  cmd/support-scheduler/Attribution.txt
  cmd/sys-mgmt-agent/Attribution.txt
  cmd/sys-mgmt-executor/Attribution.txt
  go.mod
Labels: 1-low, core-services, enhancement, geneva

#2514 Remove extra docker image tags that become malformed in the push
  Makefile
Labels: 3-high, bug, ci, geneva

#2507 Deprecate Mongo Functionality
  api/openapi/v2/system-agent.yaml
  bin/edgex-docker-launch.sh
  internal/pkg/bootstrap/handlers/database/database.go
  internal/pkg/db/db.go
  internal/pkg/db/mongo/client.go
  internal/pkg/db/mongo/client_test.go
  internal/pkg/db/mongo/models/addressable.go
  internal/pkg/db/mongo/models/channel.go
  internal/pkg/db/mongo/models/command.go
  internal/pkg/db/mongo/models/device.go
  internal/pkg/db/mongo/models/deviceprofile.go
  internal/pkg/db/mongo/models/devicereport.go
  internal/pkg/db/mongo/models/deviceservice.go
  internal/pkg/db/mongo/models/event.go
  internal/pkg/db/mongo/models/interval.go
  internal/pkg/db/mongo/models/interval_action.go
  internal/pkg/db/mongo/models/notification.go
  internal/pkg/db/mongo/models/provisionwatcher.go
  internal/pkg/db/mongo/models/reading.go
  internal/pkg/db/mongo/models/subscription.go
  internal/pkg/db/mongo/models/transmission.go
  internal/pkg/db/mongo/models/value_descriptor.go
Labels: 1-low, core-services, documentation, geneva

#2523 bugfix: update Attribution.txt path after changes to device-virtual-go
  snap/snapcraft.yaml
Labels: 1-low, ci

#2525 Remove Dead Code
  internal/pkg/acceptance/sut.go
Labels: 1-low, core-services, geneva, tech-debt
