Repository edgexfoundry/edgex-go, pull requests merged in 2022-04, with the labels that each got.

#3946 fix: replace slack.edgexfoundry.org with edgexfoundry.slack.com
  README.md
  SECURITY.md
Labels: bug, documentation, kamakura

#3965 fix: Add missing packages for local docker builds
  cmd/core-command/Dockerfile
  cmd/core-metadata/Dockerfile
  cmd/security-bootstrapper/Dockerfile
  cmd/security-proxy-setup/Dockerfile
  cmd/security-secretstore-setup/Dockerfile
  cmd/security-spiffe-token-provider/Dockerfile
  cmd/support-notifications/Dockerfile
  cmd/support-scheduler/Dockerfile
  cmd/sys-mgmt-agent/Dockerfile
Labels: bug, 1-low, build

#3967 feat(security): Use conditional go build tags for delayed start and no_messagebus
  Makefile
  README.md
  cmd/core-command/Dockerfile
  cmd/core-metadata/Dockerfile
  cmd/security-bootstrapper/Dockerfile
  cmd/security-proxy-setup/Dockerfile
  cmd/security-secretstore-setup/Dockerfile
  cmd/security-spiffe-token-provider/Dockerfile
  cmd/support-notifications/Dockerfile
  cmd/support-scheduler/Dockerfile
  cmd/sys-mgmt-agent/Dockerfile
  go.mod
  go.sum
Labels: 1-low, build

#3969 feat: Make support services include spiffe in buildtime from Makefile
  Makefile
  README.md
  cmd/security-spire-config/seed_builtin_entries.sh
Labels: enhancement, 1-low, build
