Repository edgexfoundry/edgex-go, pull requests merged in 2022-08, with the labels that each got.

#4113 ci: add local cache to optimize local docker builds
  .dockerignore
  Makefile
Labels: enhancement

#4126 feat: add management acl token and save token info to file
  cmd/security-bootstrapper/entrypoint-scripts/consul_wait_install.sh
  cmd/security-proxy-setup/res/configuration.toml
  internal/security/bootstrapper/command/setupacl/aclpolicies.go
  internal/security/bootstrapper/command/setupacl/acltokens.go
  internal/security/bootstrapper/command/setupacl/acltokens_test.go
  internal/security/bootstrapper/command/setupacl/command.go
  internal/security/bootstrapper/command/setupacl/stubregistryserver_test.go
  snap/snapcraft.yaml
Labels: enhancement, security-services, levski

#4137 build: Add option to build Core/Support services with NATS Capability
  Makefile
  README.md
  cmd/core-command/Dockerfile
  cmd/core-command/res/configuration.toml
  cmd/core-data/Dockerfile
  cmd/core-data/res/configuration.toml
  cmd/core-metadata/Dockerfile
  cmd/core-metadata/res/configuration.toml
  cmd/support-notifications/Dockerfile
  cmd/support-scheduler/Dockerfile
Labels: enhancement, build
