Repository edgexfoundry/edgex-go, pull requests merged in 2023-02, with the labels that each got.

#4312 fix: adjust redis maxclients to 1000 as default value
  cmd/security-bootstrapper/res-bootstrap-redis/configuration.toml
  internal/security/bootstrapper/helper/redis_conf.go
  internal/security/bootstrapper/helper/redis_config_test.go
  internal/security/bootstrapper/redis/config/config.go
  internal/security/bootstrapper/redis/handlers/handlers.go
Labels: security-services

#4330 feat: remove UseMessageBus from common config
  cmd/core-common-config-bootstrapper/res/configuration.yaml
Labels: tech-debt

#4327 feat: Vault tokens are now identity-based instead of anonymous
  cmd/security-file-token-provider/res/token-config.json
  cmd/security-secretstore-setup/res-file-token-provider/configuration.toml
  cmd/security-spiffe-token-provider/res/configuration.toml
  internal/security/common/tokenpolicy.go
  internal/security/common/tokenpolicy_test.go
  internal/security/common/usermanager.go
  internal/security/common/usermanager_test.go
  internal/security/fileprovider/config/config.go
  internal/security/fileprovider/provider.go
  internal/security/fileprovider/provider_test.go
  internal/security/fileprovider/tokenconfig.go
  internal/security/fileprovider/tokenconfig_test.go
  internal/security/secretstore/constants.go
  internal/security/secretstore/init.go
  internal/security/secretstore/init_test.go
  internal/security/spiffetokenprovider/config/config.go
  internal/security/spiffetokenprovider/init.go
  internal/security/spiffetokenprovider/maketoken.go
Labels: security-services, 1-low

#4349 fix: take out parallel running in unit tests to avoid timing issue
  internal/security/bootstrapper/command/setupacl/command_test.go
Labels: bug

#4348 refactor!: Replace internal topics from config with new constants
  cmd/core-command/res/configuration.toml
  cmd/core-common-config-bootstrapper/res/configuration.yaml
  cmd/core-data/res/configuration.toml
  cmd/core-metadata/res/configuration.toml
  go.mod
  go.sum
  internal/core/command/controller/messaging/external.go
  internal/core/command/controller/messaging/external_test.go
  internal/core/command/controller/messaging/internal.go
  internal/core/command/controller/messaging/internal_test.go
  internal/core/command/controller/messaging/utils.go
  internal/core/data/application/event.go
  internal/core/data/controller/http/const_test.go
  internal/core/data/controller/http/event.go
  internal/core/data/controller/http/event_test.go
  internal/core/data/controller/messaging/subscriber.go
  internal/core/data/init.go
  internal/core/metadata/application/notify.go
  internal/core/metadata/application/notify_test.go
Labels: enhancement, tech-debt, breaking-change

#4361 docs: Update Add Event Swagger for new `serviceName` parameter
  openapi/v2/core-data.yaml
Labels: documentation

#4365 fix: Add missing 'core' to event publish topic
  internal/core/data/application/event.go
Labels: bug
