Repository edgexfoundry/edgex-go, pull requests merged in 2023-03, with the labels that each got.

#4404 fix: Consume Request API fix in go-mod-messaging
  go.mod
  go.sum
Labels: bug

#4409 fix: Consume Messaging Redis Subscribe fix for Request API
  go.mod
  go.sum
  internal/core/metadata/application/notify.go
Labels: bug

#4412 fix(security): Restore ADD_PROXY_ROUTE functionality for docker NGINX
  cmd/security-bootstrapper/entrypoint-scripts/nginx_wait_install.sh
  cmd/security-proxy-setup/entrypoint.sh
Labels: bug, security-services

#4426 fix: Register healthcheck endpoint for security-proxy-auth
  internal/security/proxyauth/init.go
Labels: bug

#4432 feat: Consume watch for common Writable config changes
  go.mod
  go.sum
  internal/core/command/config/config.go
  internal/core/data/config/config.go
  internal/core/metadata/config/config.go
  internal/security/bootstrapper/config/config.go
  internal/security/bootstrapper/mosquitto/config/config.go
  internal/security/bootstrapper/redis/config/config.go
  internal/security/common/tokenpolicy_test.go
  internal/security/fileprovider/config/config.go
  internal/security/fileprovider/util_test.go
  internal/security/proxyauth/config/config.go
  internal/security/secretstore/config/config.go
  internal/security/spiffetokenprovider/config/config.go
  internal/support/notifications/config/config.go
  internal/support/scheduler/config/config.go
Labels: enhancement

#4431 docs(security): Clarify units of jwtTTL
  internal/security/config/command/proxy/adduser/command.go
Labels: documentation, security-services

#4339 feat: generate spdx sbom and add Makefile target for sbom generation
  .gitignore
  Makefile
Labels: enhancement, security_audit

#4433 refactor(security)!: Change to camelCase args for secrets-config proxy tls
  cmd/secrets-config/README.md
  internal/security/config/bootstraphandler.go
  internal/security/config/command/proxy/adduser/command.go
  internal/security/config/command/proxy/deluser/command.go
  internal/security/config/command/proxy/tls/command.go
  internal/security/config/command/proxy/tls/command_test.go
Labels: security-services, tech-debt
