Repository edgexfoundry/edgex-go, pull requests merged in 2023-04, with the labels that each got.

#4492 fix: [WIP BUG] Change SPIFFE to Spiffe in security-spiffe-token-provider YAML config
  cmd/security-spiffe-token-provider/res/configuration.yaml
Labels: bug

#4494 refactor: Adjust app service names in Spire seed script
  cmd/security-spire-config/seed_builtin_entries.sh
Labels: tech-debt

#4510 feat: Consume SecretProvider breaking changes
  go.mod
  go.sum
  internal/core/command/init.go
  internal/core/command/router.go
  internal/core/data/router.go
  internal/core/metadata/router.go
  internal/security/proxyauth/init.go
  internal/support/notifications/router.go
  internal/support/scheduler/application/scheduler/manager.go
  internal/support/scheduler/init.go
  internal/support/scheduler/router.go
Labels: tech-debt

#4509 fix: remove unnecessary service name tweaks for support services
  cmd/security-spire-config/seed_builtin_entries.sh
Labels: bug

#4521 build: update spire
  cmd/security-spire-agent/Dockerfile
  cmd/security-spire-config/Dockerfile
  cmd/security-spire-server/Dockerfile
  cmd/security-spire-server/server.conf
Labels: dependencies

#4532 feat: Consume new -d/--dev Dev Mode command-line flag
  cmd/core-command/res/configuration.yaml
  cmd/core-data/res/configuration.yaml
  cmd/core-metadata/res/configuration.yaml
  cmd/support-notifications/res/configuration.yaml
  cmd/support-scheduler/res/configuration.yaml
  go.mod
  go.sum
  internal/core/command/config/config.go
  internal/core/command/main.go
  internal/core/data/config/config.go
  internal/core/metadata/config/config.go
  internal/security/bootstrapper/command/flags_common.go
  internal/security/config/command/flags_common.go
  internal/security/proxyauth/config/config.go
  internal/security/proxyauth/main.go
  internal/security/spiffetokenprovider/config/config.go
  internal/support/notifications/config/config.go
  internal/support/notifications/main.go
  internal/support/scheduler/config/config.go
  internal/support/scheduler/main.go
Labels: enhancement
