Repository edgexfoundry/edgex-go, pull requests merged in 2023-01, with the labels that each got.

#4258 build: Update to go-mod-messaging with single broker host info
  go.mod
  go.sum
Labels: tech-debt

#4268 refactor!: Rework code for refactored MessageBus Configuration
  cmd/core-command/res/configuration.toml
  cmd/core-data/res/configuration.toml
  cmd/core-metadata/res/configuration.toml
  cmd/support-notifications/res/configuration.toml
  cmd/support-scheduler/res/configuration.toml
  go.mod
  go.sum
  internal/core/command/config/config.go
  internal/core/command/controller/messaging/external.go
  internal/core/command/controller/messaging/external_test.go
  internal/core/command/controller/messaging/internal.go
  internal/core/command/main.go
  internal/core/data/application/event.go
  internal/core/data/config/config.go
  internal/core/data/controller/messaging/subscriber.go
  internal/core/data/init.go
  internal/core/metadata/application/device.go
  internal/core/metadata/application/device_test.go
  internal/core/metadata/config/config.go
  internal/core/metadata/main.go
  internal/security/spiffetokenprovider/config/config.go
  internal/support/notifications/config/config.go
  internal/support/notifications/main.go
  internal/support/scheduler/config/config.go
  internal/support/scheduler/main.go
  openapi/v2/core-data.yaml
Labels: breaking-change

#4291 refactor!: Replace SecretStore service config with default values and overrides
  cmd/core-command/res/configuration.toml
  cmd/core-data/res/configuration.toml
  cmd/core-metadata/res/configuration.toml
  cmd/security-bootstrapper/res-bootstrap-mosquitto/configuration.toml
  cmd/security-bootstrapper/res-bootstrap-redis/configuration.toml
  cmd/security-spiffe-token-provider/res/configuration.toml
  cmd/support-notifications/res/configuration.toml
  cmd/support-scheduler/res/configuration.toml
  go.mod
  go.sum
  internal/core/command/config/config.go
  internal/core/data/config/config.go
  internal/core/metadata/config/config.go
  internal/pkg/controller/http/secret_test.go
  internal/security/bootstrapper/command/setupacl/command.go
  internal/security/bootstrapper/command/setupacl/stubregistryserver_test.go
  internal/security/bootstrapper/config/config.go
  internal/security/bootstrapper/mosquitto/config/config.go
  internal/security/bootstrapper/redis/config/config.go
  internal/security/proxy/config/config.go
  internal/security/proxy/init.go
  internal/security/spiffetokenprovider/config/config.go
  internal/security/spiffetokenprovider/init.go
  internal/support/notifications/config/config.go
  internal/support/scheduler/config/config.go
Labels: tech-debt, breaking-change

#4311 feat!: Remove old metrics collection and REST endpoint for all services
  internal/core/command/main.go
  internal/core/command/router.go
  internal/core/data/main.go
  internal/core/data/router.go
  internal/core/metadata/main.go
  internal/core/metadata/router.go
  internal/pkg/controller/http/common.go
  internal/pkg/telemetry/linux_cpu.go
  internal/pkg/telemetry/telemetry.go
  internal/pkg/telemetry/telemetry_test.go
  internal/pkg/telemetry/unimplemented_cpu.go
  internal/pkg/telemetry/windows_cpu.go
  internal/support/notifications/main.go
  internal/support/notifications/router.go
  internal/support/scheduler/main.go
  internal/support/scheduler/router.go
  openapi/v2/core-command.yaml
  openapi/v2/core-data.yaml
  openapi/v2/core-metadata.yaml
  openapi/v2/support-notifications.yaml
  openapi/v2/support-scheduler.yaml
Labels: enhancement

#4314 feat: Tweak security-bootscrapper to make it easier to disable kong/ko…
  internal/security/bootstrapper/command/gate/command.go
Labels: security-services, 1-low
