Repository edgexfoundry/edgex-go, pull requests merged in 2023-09, with the labels that each got.

#4672 refactor: Remove old InsecureSecrets backward compatibility elements
  cmd/core-common-config-bootstrapper/res/configuration.yaml
Labels: tech-debt

#4677 build: Consume latest go-mod-bootstrap with RemoveHosts flag
  go.mod
  go.sum
  internal/core/command/main.go
  internal/security/bootstrapper/command/flags_common.go
  internal/security/config/command/flags_common.go
  internal/security/kdf/methods_test.go
Labels: enhancement, ci

#4680 build: Upgrade to go-1.21, Linter1.54.2 and Alpine 3.18
  Attribution.txt
  Makefile
  cmd/core-command/Dockerfile
  cmd/core-common-config-bootstrapper/Dockerfile
  cmd/core-data/Dockerfile
  cmd/core-metadata/Dockerfile
  cmd/security-bootstrapper/Dockerfile
  cmd/security-proxy-auth/Dockerfile
  cmd/security-proxy-setup/Dockerfile
  cmd/security-secretstore-setup/Dockerfile
  cmd/security-spiffe-token-provider/Dockerfile
  cmd/security-spire-agent/Dockerfile
  cmd/security-spire-config/Dockerfile
  cmd/security-spire-server/Dockerfile
  cmd/support-notifications/Dockerfile
  cmd/support-scheduler/Dockerfile
  go.mod
Labels: ci

#4687 ci: add automated release workflow on tag creation
  .github/workflows/release.yml
Labels: ci

#4696 feat: Add new export error metrics to App Service common config
  cmd/core-common-config-bootstrapper/res/configuration.yaml
Labels: enhancement
